// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package breadcrumb

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strings"

// Size represents breadcrumb text size modifiers
type Size string

const (
	IsSmall  Size = "is-small"  // Small breadcrumb text
	IsMedium Size = "is-medium" // Medium breadcrumb text
	IsLarge  Size = "is-large"  // Large breadcrumb text
)

// Style represents breadcrumb separator styles
type Style string

const (
	HasArrowSeparator    Style = "has-arrow-separator"    // Arrow (→) separators between items
	HasBulletSeparator   Style = "has-bullet-separator"   // Bullet (•) separators between items
	HasDotSeparator      Style = "has-dot-separator"      // Dot (·) separators between items
	HasSucceedsSeparator Style = "has-succeeds-separator" // Succeeds (≻) separators between items
)

// BreadcrumbProps defines configuration for breadcrumb navigation components.
//
// Use this type to configure Bulma .breadcrumb elements which provide
// simple navigation components for showing the user's location within
// a site hierarchy. Requires only a breadcrumb container and ul list
// with automatic separator generation using CSS pseudo-elements.
type BreadcrumbProps struct {
	// Optional HTML id attribute for the breadcrumb navigation
	ID string

	// List of additional CSS classes to apply to the breadcrumb
	Class []string

	// Additional arbitrary HTML attributes
	Attributes templ.Attributes

	// Center align the breadcrumb horizontally
	IsCentered bool

	// Right align the breadcrumb (default is left aligned)
	IsRight bool

	// Text size for all breadcrumb items
	Size Size

	// Apply active state styling to the entire breadcrumb
	IsActive bool

	// Separator style between breadcrumb items
	Style Style
}

// Breadcrumb renders navigation breadcrumb components.
//
// This component renders Bulma's .breadcrumb class as a nav element,
// which creates simple navigation components for showing hierarchical
// page location. Automatically generates separators between items using
// CSS pseudo-elements. Should contain a ul list with li items, where
// the current page uses the is-active class. Perfect for site navigation
// and showing user location within content hierarchy.
func Breadcrumb(props ...BreadcrumbProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var p BreadcrumbProps
		if len(props) > 0 {
			p = props[0]
		}
		var templ_7745c5c3_Var2 = []any{"breadcrumb",
			templ.KV("is-centered", p.IsCentered),
			templ.KV("is-right", p.IsRight),
			templ.KV(string(p.Size), p.Size != ""),
			templ.KV(string(p.Style), p.Style != ""),
			templ.KV("is-active", p.IsActive),
			templ.KV(strings.Join(p.Class, " "), len(p.Class) > 0),
		}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<nav")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if p.ID != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(p.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/breadcrumb/breadcrumb.templ`, Line: 71, Col: 12}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `components/breadcrumb/breadcrumb.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, p.Attributes)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</nav>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
