// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package paragraph

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "strings"

// Size represents Bulma text size modifiers
type Size string

const (
	IsSize1 Size = "is-size-1" // 3rem
	IsSize2 Size = "is-size-2" // 2.5rem
	IsSize3 Size = "is-size-3" // 2rem
	IsSize4 Size = "is-size-4" // 1.5rem
	IsSize5 Size = "is-size-5" // 1.25rem
	IsSize6 Size = "is-size-6" // 1rem
	IsSize7 Size = "is-size-7" // 0.75rem
)

// TextColor represents Bulma text color modifiers
type TextColor string

const (
	HasTextPrimary TextColor = "has-text-primary"
	HasTextInfo    TextColor = "has-text-info"
	HasTextSuccess TextColor = "has-text-success"
	HasTextWarning TextColor = "has-text-warning"
	HasTextDanger  TextColor = "has-text-danger"
	HasTextDark    TextColor = "has-text-dark"
	HasTextLight   TextColor = "has-text-light"
)

// ParagraphProps defines properties for paragraph elements.
// Supports Bulma typography helpers for consistent text styling.
type ParagraphProps struct {
	// Optional HTML id attribute for the paragraph
	ID string
	// List of additional CSS classes to apply to the paragraph
	Class []string
	// Additional arbitrary HTML attributes
	Attributes templ.Attributes
	// Bulma text size modifier
	Size Size
	// Bulma text color modifier
	TextColor TextColor
}

// Paragraph generates HTML paragraph elements with Bulma typography support.
// Provides consistent text styling through size and color modifiers.
// Only outputs classes when corresponding properties are provided.
func Paragraph(props ...ParagraphProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var p ParagraphProps
		if len(props) > 0 {
			p = props[0]
		}
		var classes []string
		if p.Size != "" {
			classes = append(classes, string(p.Size))
		}
		if p.TextColor != "" {
			classes = append(classes, string(p.TextColor))
		}
		if len(p.Class) > 0 {
			classes = append(classes, p.Class...)
		}
		var templ_7745c5c3_Var2 = []any{strings.Join(classes, " ")}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<p")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if p.ID != "" {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " id=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(p.ID)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `elements/paragraph/paragraph.templ`, Line: 70, Col: 12}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		if len(classes) > 0 {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, " class=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `elements/paragraph/paragraph.templ`, Line: 1, Col: 0}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, p.Attributes)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
